### ISSUE TITLE
Build solution errors

### ISSUE THREAD

**Issue by Yuer-QAQ** [tiy331/Akebi-GC#1]
Errors are prompted when building the solution.
![image](https://user-images.githubusercontent.com/74231782/193503117-0d5c3df5-00f7-48f6-9bde-b45f4c703053.png)

**Comment by tiy331** [comment]
did you follow the build rules?

**Comment by tiy331** [comment]
> Errors are prompted when building the solution. ![image](https://user-images.githubusercontent.com/74231782/193503117-0d5c3df5-00f7-48f6-9bde-b45f4c703053.png)

did you follow the build rules?

**Comment by Yuer-QAQ** [comment]
> > 生成解决方案时会提示错误。![图像](https://user-images.githubusercontent.com/74231782/193503117-0d5c3df5-00f7-48f6-9bde-b45f4c703053.png)
> 
> 您是否遵循了构建规则？

![image](https://user-images.githubusercontent.com/74231782/193507383-55153bee-a76d-4aef-b4f8-97e999c35d4a.png)

Follow the method you gave ...

**Comment by tiy331** [comment]
> > > 生成解决方案时会提示错误。![图像](https://user-images.githubusercontent.com/74231782/193503117-0d5c3df5-00f7-48f6-9bde-b45f4c703053.png)
> > 
> > 
> > 您是否遵循了构建规则？
> 
> ![image](https://user-images.githubusercontent.com/74231782/193507383-55153bee-a76d-4aef-b4f8-97e999c35d4a.png)
> 
> Follow the method you gave ...

Fixed redownloda reposirtory, thank you for report

**Comment by Yuer-QAQ** [comment]
Thank you, hard work.
